services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/task_db